### ISSUE TITLE
Installation or How-to-use?

### ISSUE THREAD

**Issue by BennyAlex** [trustedtomato/yotmudo#1]
@trustedtomato 
Can you tell me how I can use it? Or isnt it working yet?

**Comment by trustedtomato** [comment]
Its a work in progress. I want to add a --help option, and for that, I want to add a helper function to my commandy package (which will generate a basic help message). Also, the output is not very helpful, so I want to develop on that too. As soon as I think everything is set to stone, I'll upload it to npm or provide a (more helpful) Installation paragraph. I'll make a roadmap, so you can see when its ready to go. You can also use/test it now by cloning the repository and running an npm build. Also, PRs are welcome. The source files are not very big, so its easy to contribute.

**Comment by trustedtomato** [comment]
OK, released it, added Getting started. It had to be renamed to yotmudo because the ytmd package existed.
